INSERT Locations(lname, latitude, longitude) VALUES('Student Union: Siesta Key Boardroom (Room 225)', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Health & Public Affairs I: 119', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Rosen College of Hospitality Management: Darden Auditorium', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('The Venue at UCF', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Research Pavilion', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Counseling and Psychological Services: Group room', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('BA 1: 115', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('UCF Art Gallery', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Student Union: Cedar Key Meeting Room (Room 223)', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Recreation and Wellness Center', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Graduate Student Center: Trevor Colbourn Hall: 213', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('CFE Arena', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Biological Sciences: 209', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('MH 395', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Greek Park', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('RWC @ Knights Plaza', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Howard Phillips Hall: 409M', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Education Complex 206L: ED206L', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Career Services and Experiential Learning: 121', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('Barbara Ying Center: 140', 28.6012, -81.2011);
INSERT Locations(lname, latitude, longitude) VALUES('The Exchange: BA1 Rm 148', 28.6012, -81.2011);

INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Intro to Mountain Biking', '<p>Ocala National Forest offers a mountain biking trail that is different than any trail in Central Florida. With winding paths through forested areas, hills that provide beautiful views, and bluff drop-offs that add a fun element to the ride, the Santos bike trail is a good introduction for anyone looking to try mountain biking for the 1st time!</p>
<p><span><strong>How do I sign up?</strong> Registration is *only* <strong>in person</strong> on a first-come, first-serve basis at the Outdoor Adventure Center (on the bottom floor of the Recreation and Wellness Center) during the OAC''s </span><span>open hours. You must have a valid UCF ID for this course. You can only register yourself. No online, phone or email registrations are accepted. There is no way to "hold a spot" for this course.<span> </span><strong>There are no refunds</strong>.<br>Please see the "Trips Policies" on for more information: <a href="http://rwc.sdes.ucf.edu/policies#p31" target="_blank">http://rwc.sdes.ucf.edu/policies#p31</a></span></p>', 'Recreation & Exercise', '2018-10-28 00:00:00', '4078236435', 'outdoor@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Recreation and Wellness Center'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Trick or Treat on Greek Street (TOTOGS)', '<p>Held around the same time as Halloween, Trick-or-Treat on Greek Street (TOTOGS) is a community-wide event in which fraternities and sororities host a variety of Halloween events for students, staff, and families in the central Orlando area.</p>', 'Social Event', '2018-10-28 12:00:00', '4078232072', 'tim.donovan@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Greek Park'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('UCF Volleyball vs. SMU', '<p>Athlete for Athlete Day.</p>
<p>Dad &amp; Daughter Day (250 free Dad &amp; Daughter T-Shirts) </p>
<p>Come out and support your Knights!</p>', 'Sports', '2018-10-28 13:00:00', '4078231000', 'tdaniel@athletics.ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='The Venue at UCF'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Guided Meditation', '<p><span>Learn how to just be. This class for students and RWC members introduces the basics of meditating and offers different guided meditations each week.</span></p>', 'Health', '2018-10-28 19:45:00', '4078235841', 'Pamela.Mills@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='RWC @ Knights Plaza'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Naval Undersea Warfare Center Division Newport RI: InfoSession and Interview Day', '<p><span>Come to learn about opportunities with Naval Undersea Warfare Center Division Newport RI. For qualified candidates, there will be an opportunity to schedule a same-day interview following the information session.</span></p>
<p><span>Please RSVP for this event in Handshake. </span></p>', 'Career/Jobs', '2018-10-29 09:00:00', '4078233424', 'csrecruit@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Career Services and Experiential Learning: 121'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Time Stretch Exhibition', '<p><strong>EXHIBITION: Time Stretch by Elizabeth / Sidebotham</strong></p>
<p><strong></strong>Erin Elizabeth is a conceptual artist and utilizes non-traditional materials such as cake and sprinkles along with gold leaf in order to explore questions about banality, celebration, and experiential value. Harry Sidebotham is first and foremost a painter. He engages in the tradition of painting, investigating scientific theories such as parallel dimension theory. They have two young children and a collaborative studio practice that assumes the identity, Elizabeth / Sidebotham.</p>
<p>Elizabeth / Sidebotham embraces the paradox presented by the intersection of a traditional domestic landscape and artistic productivity. The work reflects the sacrifices, challenges, freedom, and joy of parenthood. Fragility interplays with strength. Reverence replaces frivolity. The materials, forms, and modes of productions are infused with memory and sentimentality and exist in a state of premature nostalgia. There is profundity in the banal, but it is also spectacularly boring. Elizabeth / Sidebotham strives to capture this contradiction. <a href="http://gallery.cah.ucf.edu/exhibit/exhibition-time-stretch-by-erin-elizabeth-and-harry-sidebotham/" target="_blank">More Information</a></p>
<p><strong>Exhibition Dates: </strong>Sept. 27-Nov. 2<br><strong>Opening Reception: </strong>Thursday, Sept. 27 from 5-7 p.m.<strong><br>Artist Talk:</strong> Friday, Sept. 28 at 10 a.m.</p>', 'Arts Exhibit', '2018-10-29 10:00:00', '4078235470', 'Shannon.Lindsey@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='UCF Art Gallery'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('EndNote and RefWorks: Citing Made Easy!', '<p>Citation Management Tools allow you to dedicate more time to research! Join us for a hands-on session where you learn how to export citations from library databases, organize citations, generate bibliographies, and format citations in a Word document. Endnote &amp; RefWorks can help make managing your references and formatting citations easy! All sessions cover both tools. Please bring your own laptop to follow along with the presentation.</p>
<p><em>Students must register for all workshops through their myUCF Student Center under Graduate Students then Pathways to Success.</em></p>', 'Workshop/Conference', '2018-10-29 10:00:00', '4078232766', 'gradworkshops@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Graduate Student Center: Trevor Colbourn Hall: 213'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Thesis Defense: Fashioning Society: The Use of Facial Adornments for Social Identification in Late Postclassic Tlaxcallan, Mexico', '<p>Announcing the Final Examination of Ms. Angelica N. Costa for the degree of Master of Arts in Anthropology</p>
<p> </p>
<p>Date: October 29, 2018</p>
<p>Time: 10:00 a.m.</p>
<p>Room: HPH 409M</p>
<p> </p>
<p>Thesis title: Fashioning Society: The Use of Facial Adornments for Social Identification in Late Postclassic Tlaxcallan, Mexico</p>
<p> </p>
<p>In pre-Hispanic Central Mexico, communities frequently practiced various forms of embodying social identity through the use of facial adornments. Ornaments were placed in the ears, nose, and lips to materialize aspects of both self and collective identity. Important characteristics, such as age, gender, status, kinship, and ethnicity can be better understood through analysis of facial ornaments recovered from archaeological sites. Recent research at the Late Postclassic (AD 1420-1521) city of Tlaxcallan has provided insight into how facial ornamentation varied within the central highlands of Mexico. Typological analysis of ornaments and figurines recovered at Tlaxcallan and comparative examinations between Tlaxcalteca and Aztec historical documents has provided evidence to support varying embodiment practices between these groups. Despite their shared Nahua identity and close proximity, the Tlaxcalteca and the Aztecs chose to emphasize significantly different aspects of identity within their own social hierarchies. The persistent conflict and varying political organization between these communities is reflected in their embodiment practices. Thus, these objects have the potential to reveal how larger sociopolitical interactions can affect local collective identities. Through this I provide a better understanding of how the Tlaxcalteca and the Aztecs chose to distinguish themselves within this relatively small region in central Mexico.</p>
<p> </p>
<p>Outline of Studies:</p>
<p>Major: Anthropology</p>
<p> </p>
<p>Educational Career:</p>
<p>B.A., 2014, University of Central Florida</p>
<p> </p>
<p>Committee in Charge:</p>
<p>Dr. Sarah Barber</p>
<p>Dr. Lane Fargher</p>
<p>Dr. Brigitte Kovacevich</p>
<p>Dr. Michael Callaghan</p>
<p> </p>
<p>Approved for distribution by Sarah B. Barber, Committee Chair, on October 11, 2018.</p>
<p> </p>
<p>The public is welcome to attend.</p>', 'Speaker/Lecture/Seminar', '2018-10-29 10:00:00', '4078233790', 'tiffany.chestnut@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Howard Phillips Hall: 409M'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Mindfulness Mondays - CAPS Wellness Workshops', '<p>Looking for a more peaceful approach to your week? Come experience a new way of being and learn mindfulness skills! Part of a weekly workshop series.</p>
<p>CAPS workshops are free, require no sign-up, and space is provided on a first-come-first-serve basis to currently enrolled students.</p>', 'Workshop/Conference', '2018-10-29 12:00:00', '4078232811', 'Robert.Dwyer@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Counseling and Psychological Services: Group room'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Social Media Etiquette', '<p>Reputation, perception, and image are three key factors college students must consider when engaging in social media outlets. Learn how to establish a character consisting of integrity, civility, and respect when participating in social media.</p>
<p><span>Attendance will be taken at the workshop, free to all UCF students, no RSVP needed in advance. </span></p>
<p>Monday, October 29th from 2:00 pm - 3:00 pm</p>', 'Workshop/Conference', '2018-10-29 14:00:00', '4078235059', 'Vanity.Shields@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Student Union: Cedar Key Meeting Room (Room 223)'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Exploring How Perceptions (and Misconceptions) of Persons with Disabilities May Affect Attitudes and Behaviors', '<p><em>Open to all UCF faculty, staff, and students</em></p>
<p>Course number: DIV263</p>
<p> </p>
<p><span style="text-decoration: underline;">Monday, October 29 from 2:30pm-4:30pm</span></p>
<p>Facilitators: Sabrina Marks, Marisa Lucca, and Trisha Brockway</p>
<p>Location: Barbara Ying Center, Room 140</p>
<p> </p>
<p>The culture in the United States places significant emphasis on self-reliance and individual autonomy. This often means that persons with disabilities are expected to find ways to improve their situations and develop social relationships in a climate in which the attitudes, and ultimately the behaviors, of others present additional challenges.  The goal of this workshop is to expand awareness of the experiences of people with disabilities by encouraging workshop participants to explore their conscious and unconscious perceptions (and misconceptions) of people with disabilities, and how these may affect attitudes and behaviors.</p>', 'Workshop/Conference', '2018-10-29 14:30:00', '(407) 8236479', 'diverse@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Barbara Ying Center: 140'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Biology Seminar - Dr. Annie Page-Karjian', '<p>“Ecology and Pathophysiology of Disease in Marine Wildlife.” presented by Dr. Annie Page-Karjian </p>', 'Speaker/Lecture/Seminar', '2018-10-29 15:00:00', '4078233867', 'karen.reinemund@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Biological Sciences: 209'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Chemistry Invited Speaker - Dr. Maria Campos', '<p>"Design of Materials for Application in Agriculture"</p>
<p>UNIFAL-MG, Pocos De Caldas, Brazil</p>', 'Speaker/Lecture/Seminar', '2018-10-29 15:30:00', '4078232246', 'Michelle.Salcedo@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Health & Public Affairs I: 119'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('ICMA Speaker Series: Norton N. Bonaparte, Jr.', '<p>Norton Bonaparte, City Manager of the City of Sanford will share his experience as a public administrator overseeing a $113 million budget and over 500 employees.</p>', 'Speaker/Lecture/Seminar', '2018-10-29 16:30:00', '3214828333', 'beale.stephen@knights.ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='BA 1: 115'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Overeaters Anonymous', '<p>OA is not just about weight loss, weight gain or maintenance, obesity or diets. The OA program offers physical, emotional and spiritual recovery for those who suffer from compulsive eating. Members find recovery on all three levels by following a Twelve-Step program patterned after Alcoholics Anonymous. Members who recover through the Twelve Steps find that yo-yo dieting is a thing of the past. They no longer wish to return to eating compulsively.</p>', 'Health', '2018-10-29 17:30:00', '4078230476', 'crc@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Research Pavilion'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('UCF Men''s Basketball vs. Flagler', '<p>Get your first look at the Knights in their exhibition against Flagler.</p>
<p>See their full schedule here: <a href="http://ucfknights.com/SportSelect.dbml?&amp;DB_OEM_ID=34100&amp;SPID=181628&amp;SPSID=1115487" target="_blank">http://ucfknights.com/SportSelect.dbml?&amp;DB_OEM_ID=34100&amp;SPID=181628&amp;SPSID=1115487</a>.</p>', 'Sports', '2018-10-29 19:00:00', '4078231000', 'acesarano@athletics.ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='CFE Arena'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Al-Anon: Serenity Now', '<p>This meeting is held every Monday (unless otherwise noted on the UCF calendar) from 7pm to 8pm at <span>the</span><span>Point @ UCF in Research Park</span>: SUITE 135, 12424 Research Pkwy #250, Orlando, FL.</p>
<p> The Al-Anon Family Groups are a fellowship of relatives and friends of alcoholics who share their experience, strength and hope in order to solve their common problems. We believe alcoholism is a family illness, and that changed attitudes can aid recovery. Al-Anon has but one purpose: to help friends and families of alcoholics. We do this by practicing the Twelve Steps, by welcoming and giving comfort to families and friends of alcoholics, and by giving understanding and encouragement to the alcoholic. Whether the alcoholic is still drinking or not, Al-Anon offers hope and recovery to all people affected by the alcoholism of a loved one or friend.</p>
<p> </p>
<p>For more information about this meeting visit <a href="http://www.shs.ucf.edu/crc" target="_blank">www.StudentHealth.ucf.edu/CRC</a> or call the Al-Anon Family Groups Helpline at (800) 344-2666.</p>', 'Meeting', '2018-10-29 19:00:00', '4078230476', 'crc@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='Research Pavilion'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Heartfulness Meditation', '<p><span>Join us for a session of Heartfulness Meditation. </span></p>
<p><span>Heartfulness Meditation is a simple, practical technique that you can use alongside any other form of yoga, meditation or spiritual practice. In a few minutes, you will learn how to truly relax and feel the lightness and joy of your true nature. You don’t need to know how to meditate or to believe in a particular system or philosophy. The Heartfulness technique shows us to gently turn our attention towards our heart and experience that inner presence for ourselves.</span></p>', 'Academic', '2018-10-29 19:00:00', '3219454322', 'heartfulnessucf@gmail.com', '1', '1', (SELECT lid FROM Locations WHERE lname='Student Union: Siesta Key Boardroom (Room 225)'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Time Stretch Exhibition', '<p><strong>EXHIBITION: Time Stretch by Elizabeth / Sidebotham</strong></p>
<p><strong></strong>Erin Elizabeth is a conceptual artist and utilizes non-traditional materials such as cake and sprinkles along with gold leaf in order to explore questions about banality, celebration, and experiential value. Harry Sidebotham is first and foremost a painter. He engages in the tradition of painting, investigating scientific theories such as parallel dimension theory. They have two young children and a collaborative studio practice that assumes the identity, Elizabeth / Sidebotham.</p>
<p>Elizabeth / Sidebotham embraces the paradox presented by the intersection of a traditional domestic landscape and artistic productivity. The work reflects the sacrifices, challenges, freedom, and joy of parenthood. Fragility interplays with strength. Reverence replaces frivolity. The materials, forms, and modes of productions are infused with memory and sentimentality and exist in a state of premature nostalgia. There is profundity in the banal, but it is also spectacularly boring. Elizabeth / Sidebotham strives to capture this contradiction. <a href="http://gallery.cah.ucf.edu/exhibit/exhibition-time-stretch-by-erin-elizabeth-and-harry-sidebotham/" target="_blank">More Information</a></p>
<p><strong>Exhibition Dates: </strong>Sept. 27-Nov. 2<br><strong>Opening Reception: </strong>Thursday, Sept. 27 from 5-7 p.m.<strong><br>Artist Talk:</strong> Friday, Sept. 28 at 10 a.m.</p>', 'Arts Exhibit', '2018-10-30 10:00:00', '4078235470', 'Shannon.Lindsey@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='UCF Art Gallery'));
INSERT INTO Events(title, descr, category, dtime, cphone, cemail, urestriction, approved, lid) VALUES('Faculty Collective Bargaining Notice', '<p>The next collective bargaining session between the University of Central Florida Board of Trustees and the United Faculty of Florida will take place on Tuesday, October 30, 2018, from 10 a.m. – 2 p.m. in MH 395.</p>', 'Meeting', '2018-10-30 10:00:00', '4078235420', 'cpiper@ucf.edu', '1', '1', (SELECT lid FROM Locations WHERE lname='MH 395'));
